### ISSUE TITLE
De nieuwe achtergrondkaart werkt nog niet

### ISSUE THREAD

**Issue by kad-beekw** [kadaster/datascience-comunica-client#3]
@rubensworks De nieuwe achtergrondkaart lijkt goed ingesteld in het bestand `settings.json`, maar wordt nog niet gebruikt wanneer de applicatie gebouwd wordt.  Zie bijvoorbeeld de door mij gebouwde versie op <http://localhost:4000/demonstrators/comunica/>.

Ik volg daarbij de volgende stappen:
1. `npm install`
2. `npm build`
3. Kopieer de inhoud van de `build/` directory.

**Comment by rubensworks** [comment]
Ik vermoed dat dit gaat over het aanpassen van de oude (deprecated) map URLs naar de nieuwe?

> De nieuwe achtergrondkaart lijkt goed ingesteld in het bestand settings.json, maar wordt nog niet gebruikt wanneer de applicatie gebouwd wordt. 

Welke config aanpassing probeer je precies te doen?

> Zie bijvoorbeeld de door mij gebouwde versie op http://localhost:4000/demonstrators/comunica/.

Kan het zijn dat de verkeerde link vermeld is?

**Comment by kad-beekw** [comment]
> Ik vermoed dat dit gaat over het aanpassen van de oude (deprecated) map URLs naar de nieuwe?

Klopt de BRT heeft een andere link sinds kort.  We proberen dit voor alle applicaties te updaten.

> Welke config aanpassing probeer je precies te doen?

Ik dacht dat jouw aanpassing op regel <https://github.com/kadaster/datascience-comunica-client/blob/master/settings.json#L14> al voldoende was.  Ik heb gebouwd en gedeployed, maar de oude BRT wordt nog steeds gebruikt.

> Kan het zijn dat de verkeerde link vermeld is?

De goede link is <https://labs.kadaster.nl/demonstrators/comunica/>.

**Comment by rubensworks** [comment]
> Ik dacht dat jouw aanpassing op regel https://github.com/kadaster/datascience-comunica-client/blob/master/settings.json#L14 al voldoende was. Ik heb gebouwd en gedeployed, maar de oude BRT wordt nog steeds gebruikt.

Is dit net niet de URL die deprecated is?
Deze werkte eerder op https://kadaster.github.io/datascience-comunica-client/, maar nu niet meer (zonder aanpassing aan de config).

Aangezien de deprecated img getoond wordt lijken de settings correct te werken, anders zouden de default mapbox maps gebruikt moeten worden: https://github.com/comunica/jQuery-Widget.js/blob/feature/solid-auth/settings.json#L14

**Comment by kad-beekw** [comment]
Excuses @rubensworks!  Ik had de oude en de nieuwe BRT achtergrondkaart links verwisseld.  Nu heb ik de juiste versie geconfigureerd en gecommit.

Comunica werkt weer prima met Kadaster data, zie <https://labs.kadaster.nl/demonstrators/comunica/>.

**Comment by rubensworks** [comment]
Super, blij dat het opgelost is! :-)
